name: build
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run : pip install dash-core-components==0.5.0
      - run : pip install dash-html-components==0.6.0
      - run : pip install dash-renderer==0.7.2
      - run : pip install dash==0.17.4
      - run : pip install gunicorn==19.6.0